# -*- coding: utf-8 -*-
"""AC_fault_detec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1poq3esU6c46_yJ6LYn_4qdwTAqw1bYQL
"""

# 구글 코랩에서 한글 폰트를 설치합니다.
!apt-get update -qq
!apt-get install -qq fonts-nanum

# 설치된 폰트를 확인합니다.
!fc-list :lang=ko

# ╔══════════════════════════════════════════════════════╗
# ║   에어컨 고장 유형별 소비전력 분석기 (Colab 버전)       ║
# ║   MDPI 2024 실측 데이터 기반                          ║
# ╚══════════════════════════════════════════════════════╝

import numpy as np
import matplotlib.pyplot as plt
import glob
from pathlib import Path

plt.rcParams['figure.dpi'] = 120

# ── 설정: 데이터 폴더 경로 ─────────────────────────────
# 코랩 파일과 같은 폴더면 "./"
# 하위 폴더면 예: "./data/" 또는 "/content/data/"
DATA_DIR = "/content/drive/MyDrive/Colab Notebooks/LG전자DX스쿨/Project/LG DX/에어컨 고장/./"
# ──────────────────────────────────────────────────────

FAULT_LABELS = {
    'FL':       '정상 (Faultless)',
    'CI30':     '콘덴서 30% 막힘',
    'CI60':     '콘덴서 60% 막힘',
    'FI50':     '필터 50% 막힘',
    'CD30':     '커패시터 30% 노후',
    'CD30CI30': '커패시터+콘덴서30%',
    'CD30CI60': '커패시터+콘덴서60%',
    'CD30FI50': '커패시터+필터',
    'CI60FI50': '콘덴서+필터',
}

def get_label(filename):
    key = Path(filename).stem.replace('Dataset_', '').replace('dataset_', '')
    return FAULT_LABELS.get(key, key)

def analyze_file(path):
    try:
        data = np.loadtxt(path, skiprows=2, max_rows=1800000)
        current = data[:, 0]
        voltage = data[:, 1]
        rms_i = np.sqrt(np.mean(current**2))
        rms_v = np.sqrt(np.mean(voltage**2))
        power = rms_i * rms_v * 0.9
        return {
            'label':     get_label(path),
            'rms_i':     rms_i,
            'rms_v':     rms_v,
            'power':     power,
            'current':   current,
            'power_inc': 0.0,
            'status':    '',
        }
    except Exception as e:
        print(f"  ⚠️  {Path(path).name} 읽기 실패: {e}")
        return None

# ── 1. 파일 탐색 ───────────────────────────────────────
txt_files = sorted(glob.glob(DATA_DIR + '*.txt'))
if not txt_files:
    raise FileNotFoundError(f"'{DATA_DIR}' 에 txt 파일이 없어요. DATA_DIR 경로를 확인해 주세요.")

print(f"📂 발견된 파일 {len(txt_files)}개:")
for f in txt_files:
    print(f"   {Path(f).name}")

# ── 2. 분석 ───────────────────────────────────────────
print("\n⏳ 분석 중...")
results = []
for path in txt_files:
    r = analyze_file(path)
    if r:
        results.append(r)
        print(f"  ✅ {Path(path).name} → {r['power']:.1f} W")

# FL 기준값
baseline = next(
    (r for r in results if '정상' in r['label']),
    results[0]
)
print(f"\n📌 기준: {baseline['label']} ({baseline['power']:.1f} W)")

for r in results:
    r['power_inc'] = (r['power'] - baseline['power']) / baseline['power'] * 100

# ── 3. 결과 출력 (임계값 설정 전) ──────────────────────
print("\n" + "="*55)
print(f"  {'고장 유형':<25} {'소비전력(W)':<12} {'증가율'}")
print("-"*55)
for r in sorted(results, key=lambda x: x['power_inc']):
    inc    = f"{r['power_inc']:+.2f}%" if r != baseline else "기준 (0%)"
    marker = " ◀ 기준" if r == baseline else ""
    print(f"  {r['label']:<25} {r['power']:<12.1f} {inc}{marker}")
print("="*55)

# ── 4. 임계값 직접 입력 ────────────────────────────────
print("\n위 증가율을 보고 임계값을 설정해 주세요.")
print("예) 필터 막힘 +2.4% / 커패시터 노후 +8.3% 참고\n")

while True:
    try:
        alert = float(input("  점검 권장 임계값 (%) → +"))
        warn  = float(input("  즉시 점검 임계값 (%) → +"))
        if warn <= alert:
            print("  ⚠️  즉시 점검 값이 점검 권장보다 커야 해요.\n")
            continue
        break
    except ValueError:
        print("  숫자를 입력해 주세요.")

print(f"\n✅ 임계값 확정: 점검 권장 +{alert}% / 즉시 점검 +{warn}%")

# ── 5. 판정 ───────────────────────────────────────────
def get_status(r):
    if r == baseline:           return '✅ 정상'
    if r['power_inc'] >= warn:  return '🔴 즉시 점검'
    if r['power_inc'] >= alert: return '⚠️  점검 권장'
    return '✅ 정상 범위'

for r in results:
    r['status'] = get_status(r)

print("\n" + "="*65)
print(f"  {'고장 유형':<25} {'소비전력(W)':<12} {'증가율':<10} {'판정'}")
print("-"*65)
for r in sorted(results, key=lambda x: x['power_inc']):
    inc = f"{r['power_inc']:+.2f}%" if r != baseline else "기준"
    print(f"  {r['label']:<25} {r['power']:<12.1f} {inc:<10} {r['status']}")
print("="*65)

# ── 6. 그래프 ──────────────────────────────────────────
sorted_r     = sorted(results, key=lambda x: x['power_inc'])
short_labels = [r['label'].replace(' (Faultless)', '') for r in sorted_r]

def bar_color(inc):
    if inc < alert: return '#2ecc71'
    if inc < warn:  return '#f39c12'
    return '#e74c3c'

fig, axes = plt.subplots(1, 3, figsize=(18, 5), facecolor='#111')
fig.suptitle(
    f'에어컨 고장 유형별 소비전력 분석 (MDPI 2024 실측 데이터)\n'
    f'점검 권장 +{alert}% / 즉시 점검 +{warn}%',
    fontsize=13, color='white', fontweight='bold')

# 소비전력 바
ax1 = axes[0]
ax1.set_facecolor('#1a1a1a')
bars = ax1.barh(short_labels, [r['power'] for r in sorted_r],
                color=[bar_color(r['power_inc']) for r in sorted_r],
                edgecolor='#333', height=0.6)
ax1.axvline(x=baseline['power'], color='#2ecc71',
            linestyle='--', linewidth=1.5, alpha=0.7)
ax1.set_title('소비전력 (W)', color='white')
ax1.tick_params(colors='#ccc')
ax1.spines[:].set_color('#444')
ax1.grid(axis='x', color='#333', linewidth=0.5)
for bar, r in zip(bars, sorted_r):
    ax1.text(r['power'] + 3, bar.get_y() + bar.get_height()/2,
             f"{r['power']:.0f}W", va='center', color='white', fontsize=9)

# 증가율 바
ax2 = axes[1]
ax2.set_facecolor('#1a1a1a')
incs  = [r['power_inc'] for r in sorted_r]
bars2 = ax2.barh(short_labels, incs,
                 color=[bar_color(v) for v in incs],
                 edgecolor='#333', height=0.6)
ax2.axvline(x=alert, color='#f39c12', linestyle='--',
            linewidth=1.5, alpha=0.9, label=f'점검권장 +{alert}%')
ax2.axvline(x=warn,  color='#e74c3c', linestyle='--',
            linewidth=1.5, alpha=0.9, label=f'즉시점검 +{warn}%')
ax2.legend(fontsize=8, facecolor='#222', labelcolor='white')
ax2.set_title('정상 대비 증가율 (%)', color='white')
ax2.tick_params(colors='#ccc')
ax2.spines[:].set_color('#444')
ax2.grid(axis='x', color='#333', linewidth=0.5)
for bar, val in zip(bars2, incs):
    label = '기준' if abs(val) < 0.01 else f'{val:+.1f}%'
    ax2.text(max(val, 0) + 0.1, bar.get_y() + bar.get_height()/2,
             label, va='center', color='white', fontsize=9)

# 전류 파형
ax3 = axes[2]
ax3.set_facecolor('#1a1a1a')
wave_colors = ['#2ecc71','#f39c12','#e74c3c','#3498db',
               '#9b59b6','#e67e22','#1abc9c','#e91e63']
t = np.linspace(0, 0.05, 1500)
for i, r in enumerate(results):
    ax3.plot(t, r['current'][:1500],
             color=wave_colors[i % len(wave_colors)],
             linewidth=1.2, alpha=0.85,
             label=r['label'].replace(' (Faultless)', ''))
ax3.set_title('전류 파형 비교 (첫 0.05초)', color='white')
ax3.set_xlabel('시간 (s)', color='#aaa')
ax3.set_ylabel('전류 (A)', color='#aaa')
ax3.tick_params(colors='#aaa')
ax3.spines[:].set_color('#444')
ax3.grid(color='#333', linewidth=0.5)
ax3.legend(fontsize=7, facecolor='#222', labelcolor='white')

plt.tight_layout()
plt.savefig('ac_fault_analysis.png', dpi=150,
            bbox_inches='tight', facecolor='#111')
plt.show()

# ── 7. CSV 저장 ────────────────────────────────────────
csv_path = 'ac_fault_results.csv'
with open(csv_path, 'w', encoding='utf-8-sig') as f:
    f.write('고장유형,소비전력(W),RMS전류(A),RMS전압(V),증가율(%),판정\n')
    for r in sorted(results, key=lambda x: x['power_inc']):
        f.write(f"{r['label']},{r['power']:.1f},{r['rms_i']:.4f},"
                f"{r['rms_v']:.2f},{r['power_inc']:+.2f},{r['status']}\n")

print(f"\n📊 그래프 저장: ac_fault_analysis.png")
print(f"📋 결과 CSV:   {csv_path}")
print("✅ 분석 완료!")

